name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      scalaVersion:
        description: 'Version of Scala to run'  
        required: false
        default: '3.5.2'
        type: string

jobs:
  build:
    name: ${{matrix.os}}, ${{matrix.scala_version}}
    strategy:
      fail-fast: false
      matrix:
        scala_version: ["2.13.14", "3.3.4", "3.5.1", "3.6.2-RC1-bin-20241102-01288d2-NIGHTLY", "3.6.0-RC1-bin-20240919-ba9e59a-NIGHTLY"]
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6
      
      - uses: sbt/setup-sbt@v1

      - name: Setup
        run: |
          PLATFORM="$(uname)"
          if [ $PLATFORM == "Darwin" ]; then
            brew install sbt 
          else
            echo "It's a Linux"
          fi

      - name: Check formatting
        shell: bash
        run: |
          sbt -Dsbt.task.timings=true 'clean;compile' # 2>&1 | grep "root / Compile / compileIncremental"
        env:
          SCALA_VERSION: ${{ matrix.scala_version }}

